on:
  push:

permissions:
  contents: read
  actions: read
  checks: write

env:
  DOTNET_VERSION: '9.x'

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
        env:
          OAuth__Authority: ${{ vars.AUTH0_AUTHORITY }}
          OAuth__Audience: ${{ vars.AUTH0_AUDIENCE }}
          Tests__SmokeTest__Auth__AccessTokens__Admin: ${{ secrets.AUTH0_GITHUB_ADMIN_ACCESS_TOKEN }}
          Tests__SmokeTest__Auth__AccessTokens__Player1: ${{ secrets.AUTH0_GITHUB_PLAYER1_ACCESS_TOKEN }}
          Tests__SmokeTest__Auth__AccessTokens__Player2: ${{ secrets.AUTH0_GITHUB_PLAYER2_ACCESS_TOKEN }}

      - name: Generate unit test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit test report
          path: ./src/UnitTests/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Generate integration test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Integration test report
          path: ./src/IntegrationTests/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Generate smoke test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Smoke test report
          path: ./src/SmokeTests/TestResults/test-results.trx
          reporter: dotnet-trx