on:
  push:

permissions:
  contents: read
  actions: read
  checks: write

env:
  DOTNET_VERSION: '9.x'

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
        env:
          OAuth__Authority: ${{ vars.AUTH0_AUTHORITY }}
          OAuth__Audience: ${{ vars.AUTH0_AUDIENCE }}
          SmokeTest__OAuth__Credentials__Admin__ClientId: ${{ secrets.AUTH0_GITHUB_ADMIN_CLIENT_ID }}
          SmokeTest__OAuth__Credentials__Admin__ClientSecret: ${{ secrets.AUTH0_GITHUB_ADMIN_CLIENT_SECRET }}
          SmokeTest__OAuth__Credentials__Player1__ClientId: ${{ secrets.AUTH0_GITHUB_PLAYER1_CLIENT_ID }}
          SmokeTest__OAuth__Credentials__Player1__ClientSecret: ${{ secrets.AUTH0_GITHUB_PLAYER1_CLIENT_SECRET }}
          SmokeTest__OAuth__Credentials__Player2__ClientId: ${{ secrets.AUTH0_GITHUB_PLAYER2_CLIENT_ID }}
          SmokeTest__OAuth__Credentials__Player2__ClientSecret: ${{ secrets.AUTH0_GITHUB_PLAYER2_CLIENT_SECRET }}

      - name: Generate unit test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit test report
          path: ./src/UnitTests/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Generate integration test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Integration test report
          path: ./src/IntegrationTests/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Generate smoke test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Smoke test report
          path: ./src/SmokeTests/TestResults/test-results.trx
          reporter: dotnet-trx